
#spring:
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://127.0.0.1:3306/sgscdb?serverTimezone=UTC&useUnicode=yes&characterEncoding=UTF-8&useSSL=false&zeroDateTimeBehavior=convertToNull&allowPublicKeyRetrieval=true&useSSL=false
#    username: root
#    password: 1234

spring:
  datasource:
    testdb1:
      maximum-pool-size: 4
      jdbc-url: jdbc:mysql://127.0.0.1:3306/sgscdb?serverTimezone=UTC&useUnicode=yes&characterEncoding=UTF-8&useSSL=false&zeroDateTimeBehavior=convertToNull&allowPublicKeyRetrieval=true&useSSL=false
      username: root
      password: 1234
      driver-class-name: com.mysql.cj.jdbc.Driver
    
    testdb2:
      maximum-pool-size: 4
      jdbc-url: jdbc:mysql://127.0.0.1:3306/sgscdb?serverTimezone=UTC&useUnicode=yes&characterEncoding=UTF-8&useSSL=false&zeroDateTimeBehavior=convertToNull&allowPublicKeyRetrieval=true&useSSL=false
      username: root
      password: 1234
      driver-class-name: com.mysql.cj.jdbc.Driver

spring.redis:
  host: localhost
  port: 6379

spring.jwt.secret: SGSC_AAA

server.port: 80
server.servlet.context-path: /spring

jpa:
  show-sql: true
  hibernate:
    ddl-auto: create


myconf:
    list:
        - hoge
        - fuga
        - piyo

spring.logging.level.org.springframework.web: DEBUG

spring.mvc.view.prefix: /WEB-INF/jsp/
spring.mvc.view.suffix: .jsp



#spring.primary.datasource.jdbc-url: jdbc:oracle:thin:@localhost:1521:orcl
#spring.primary.datasource.username: system
#spring.primary.datasource.password: 1234qwer
#spring.primary.datasource.driverClassName: oracle.jdbc.OracleDriver
 
#spring.secondary.datasource.jdbc-url: jdbc:oracle:thin:@localhost:1521:orcl
#spring.secondary.datasource.username: system
#spring.secondary.datasource.password: 1234qwer
#spring.secondary.datasource.driverClassName: oracle.jdbc.OracleDriver
